language: node_js
node_js:
  - "4"
  - "6"
  - "7"
  - "8"
before_install:
  - npm i -g greenkeeper-lockfile@1
  - npm i -g coveralls
install:
  - npm install
before_script:
  - greenkeeper-lockfile-update
script:
  - npm test
after_script:
  - greenkeeper-lockfile-upload
notifications:
  email:
    on_failure: change
jobs:
  include:
    - stage: lint
      node_js: "8"
      script:
        - npm run lint:eslint
        - npm run lint:prettier
    - stage: coverage
      node_js: "8"
      script:
        - npm run test -- --coverage && cat ./coverage/lcov.info | coveralls
